-- Create Database
CREATE DATABASE COLLAGE;

-- Use Database
USE COLLAGE;

-- Create Student Table
CREATE TABLE STUDENT(
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT NOT NULL
);

-- Insert Data
INSERT INTO STUDENT VALUES(1,'PRASHANT',22);
INSERT INTO STUDENT VALUES(2,'JAY',27);
INSERT INTO STUDENT VALUES(3,'RAM',25);
INSERT INTO STUDENT VALUES(4,'NEHA',21);

-- Display Data
SELECT * FROM STUDENT;
