CREATE DATABASE COLLAGE;
USE COLLAGE;

CREATE TABLE ABC(
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT
);

INSERT INTO ABC VALUES(1,'A',18);
INSERT INTO ABC VALUES(2,'B',22);
INSERT INTO ABC VALUES(3,'C',25);

SELECT * FROM ABC WHERE AGE > 20;
